name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare
    steps:
      - uses: actions/checkout@v2
      - name: Publish as a worker
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: 4uSxkK2lJT6cVDTnQmAhytrVn8cPsb1CNyuy9Edw
